In [2]:
import numpy as np

In [3]:
# create arrays with zeros, ones and constants

zeros = np.zeros(10)
ones = np.ones(10)
constants = np.full(10, 3.0)

In [4]:
print(zeros)
print(ones)
print(constants)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [5]:
# converting lists to arrays

list_example = [1, 2, 3, 4, 5, 6]

list_to_array = np.array(list_example)

In [6]:
print(list_to_array)

[1 2 3 4 5 6]


In [7]:
# generating ranges of numbers

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# creating arrays with linear spacing

np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
# multi-dimensional arrays

zeros_multi = np.zeros((2, 2))
ones_multi = np.ones((2, 2))
constants_multi = np.full((2, 2), 3)

In [10]:
print(zeros_multi)
print(ones_multi)
print(constants_multi)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3 3]
 [3 3]]


In [11]:
# indexing and slicing arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
print(arr[0, :])

[1 2 3]


In [13]:
print(arr[:, 0])

[1 4]


In [14]:
# generating random arrays

# for reproducibility fix the seed

SEED = 2
np.random.seed(seed=SEED)

# generating random numbers between zero and one
print(np.random.rand(5, 2))

# generate from a normal distribution with mean 0 and std 1
print(np.random.randn(5, 2))

# generate from a random distribution of integers
print(np.random.randint(low = 0, high = 100, size = (5, 2)))

[[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]
[[ 0.55145404  2.29220801]
 [ 0.04153939 -1.11792545]
 [ 0.53905832 -0.5961597 ]
 [-0.0191305   1.17500122]
 [-0.74787095  0.00902525]]
[[83 31]
 [66 80]
 [52 76]
 [50  4]
 [90 63]]


In [15]:
# Array operations

# element wise operations on one array
print(arr)
arr = arr + 1
print(arr)
arr = arr * 2
print(arr)
arr = arr / 2
print(arr)
arr = arr - 1
print(arr)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[[ 4  6  8]
 [10 12 14]]
[[2. 3. 4.]
 [5. 6. 7.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
# element wise operations between multiple arrays

arr1 = np.ones(4)
arr2 = np.full(4, 3)

print(arr1 / arr2)
print(arr1 * arr2)
print(arr1 + arr2)
print(arr1 - arr2)

[0.33333333 0.33333333 0.33333333 0.33333333]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[-2. -2. -2. -2.]


In [17]:
# comparison operations, filtering operations

arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2

print(arr)
print(greater_than_2)

[1 2 3 4]
[False False  True  True]


In [18]:
selected_elements = arr[arr > 1]  # Gets elements greater than 1

In [19]:
selected_elements

array([2, 3, 4])

In [20]:
arr

array([1, 2, 3, 4])

In [21]:
# summary operations

min_value = arr.min()    # Minimum value
print(min_value)
max_value = arr.max()    # Maximum value
print(max_value)
sum_value = arr.sum()    # Sum of all elements
print(sum_value)
mean_value = arr.mean()  # Mean (average) value
print(mean_value)
std_deviation = arr.std()  # Standard deviation
print(std_deviation)

1
4
10
2.5
1.118033988749895


In [22]:
# sorting

np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [23]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [24]:
pred

array([0.44, 0.03, 0.55, 0.44])

In [27]:
pred.sort()

In [28]:
pred

array([0.03, 0.44, 0.44, 0.55])

In [29]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [30]:
idx = pred.argsort()

In [31]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [32]:
# reshaping

mat = np.arange(6)
mat

array([0, 1, 2, 3, 4, 5])

In [42]:
mat = mat.reshape((2, 3))

In [46]:
# putting arrays together

# concatenate

vec = np.arange(2)

In [38]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [39]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [40]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [43]:
np.hstack([mat, mat])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [44]:
np.concatenate([mat, mat])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [47]:
np.column_stack([vec, mat])

array([[0, 0, 1, 2],
       [1, 3, 4, 5]])

In [48]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1]])